[#api_BooleanStreamHandler]
= Boolean Stream Handler API
:toc:
:source-highlighter: pygments
:source-language: c++
:source_subs: attributes,specialchars,macros
ifndef::xref-rel-dir[]
:xref-rel-dir: ../../
endif::[]

Include this API as

----
#include <wtk/BooleanStreamHandler.h>
----

Members of this API live in the following namespace

----
namespace wtk { ...
----

[#class_BooleanStreamHandler]
== `class BooleanStreamHandler`
The `wtk::BooleanStreamHandler` is a virtual class for the user to implement with callbacks for the xref:{xref-rel-dir}api/wtk/Parser.adoc#api_Parser[Parser API] to use when stream parsing.

[#BooleanStreamHandler_setLineNumber]
=== `virtual void setLineNumber(size_t const line)`
If the Parser supports line-numbering, it will use this callback to set the current line number before a gate's callback is invoked.

----
virtual void setLineNum(size_t const line);
----

[#BooleanStreamHandler_handleInstance]
=== `virtual void handleInstance(wtk::index_t const idx)`
Called when an `@instance` directive is reached.

----
virtual void handleInstance(wtk::index_t const idx);
----

[#BooleanStreamHandler_handleShortWitness]
=== `virtual void handleShortWitness(wtk::index_t const idx)`
Called when an `@short_witness` directive is reached.

----
virtual void handleShortWitness(wtk::index_t const idx);
----

[#BooleanStreamHandler_handleXor]
=== `virtual void handleXor(wtk::index_t const out, wtk::index_t const left, wtk::index_t const right)`
Called when an `@xor` directive is reached.

----
virtual void handleXor(wtk::index_t const out, wtk::index_t const left, wtk::index_t const right);
----

[#BooleanStreamHandler_handleAnd]
=== `virtual void handleAnd(wtk::index_t const out, wtk::index_t const left, wtk::index_t const right)`
Called when an `@and` directive is reached.

----
virtual void handleAnd(wtk::index_t const out, wtk::index_t const left, wtk::index_t const right);
----

[#BooleanStreamHandler_handleNot]
=== `virtual void handleNot(wtk::index_t const out, wtk::index_t const in)`
Called when a `@not` directive is reached.

----
virtual void handleNot(wtk::index_t const out, wtk::index_t const in);
----

[#BooleanStreamHandler_handleAssign]
=== `virtual void handleAssign(wtk::index_t const out, uint8_t const val)`
Called when a constant assignment directive is reached.

----
virtual void handleAssign(wtk::index_t const out, uint8_t const val);
----

[#BooleanStreamHandler_handleCopy]
=== `virtual void handleCopy(wtk::index_t const out, wtk::index_t const in)`
Called when a copy directive is reached.

----
virtual void handleCopy(wtk::index_t const out, wtk::index_t const in);
----

[#BooleanStreamHandler_handleAssertZero]
=== `virtual void handleAssertZero(wtk::index_t const in)`
Called when an `@assert_zero` directive is reached.

----
virtual void handleAssertZero(wtk::index_t const in);
----

[#BooleanStreamHandler_handleDeleteSingle]
=== `virtual void handleDeleteSingle(wtk::index_t const in)`
Called when a `@delete` directive with a single argument is reached.

----
virtual void handleDeleteSingle(wtk::index_t const in);
----

[#BooleanStreamHandler_handleDeleteRange]
=== `virtual void handleDeleteRange(wtk::index_t const first, wtk::index_t const last)`
Called when a `@delete` directive with a range argument is reached.
The range is inclusive on both ends.

----
virtual void handleDeleteRange(wtk::index_t const first, wtk::index_t const last);
----

[#BooleanStreamHandler_handleEnd]
=== `virtual void handleEnd()`
Called after the last directive is reached.

----
virtual void handleEnd();
----
