[#api_Parser]
= Parser API
:toc:
:source-highlighter: pygments
:source-language: c++
:source_subs: attributes,specialchars,macros
ifndef::xref-rel-dir[]
:xref-rel-dir: ../../
endif::[]

Include this API as

----
#include <wtk/Parser.h>
----

Members of this API live in the following namespace

----
namespace wtk { ...
----

The Parser API is parameterized on a `Number_T` template.
`Number_T` should be integer-like enough to be parsed from a string.
This API is abstract and implemented by parsers for various IR formats.

[#struct_Parser]
== `template<typename Number_T> struct Parser`
The Parser will read the IR's front matter before delegating to an xref:#struct_ArithmeticParser[`wtk::ArithmeticParser<Number_T>`] or a xref:#struct_BooleanParser[`wtk::BooleanParser`].

The struct's public data members are set to default values (mostly 0) at construction and assigned concrete values as parse methods are invoked.
The parser methods are expected to be called in the correct order (xref:#Parser_parseHeader[`parseHeader()`], xref:#Parser_parseResource[`parseResource()`], and finally for relations only xref:#Parser_parseParameters[`parseParameters()`]).
A helper for calling them in the correct order is provided as xref:#Parser_parseHdrResParams[`parseHdrResParams()`].

When the front-matter has been parsed, one of xref:#Parser_arithmetic[`arithmetic()`], xref:#Parser_arithmetic64[`arithmetic64()`],  xref:#Parser_arithmetic32[`arithmetic32()`], or xref:#Parser_boolean[`boolean()`] may be invoked to delegate parsing the body to either of xref:#struct_ArithmeticParser[`wtk::ArithemticParser<...>`]
or xref:#struct_BooleanParser[`wtk::BooleanParser`].
[#Parser_parseHeader]
=== `bool parseHeader()`
Parses the resources header section setting the following attributes.

- xref:#Parser_version[`struct { ... } version`]
- xref:#Parser_characteristic[`Number_T characteristic`]
- xref:#Parser_degree[`size_t degree`]

Returns `true` on success, false if a parse error occurs.

----
virtual bool parseHeader() = 0;
----

[#Parser_parseResource]
=== `bool parseResource()`
Parses the resource type and sets the xref:#Parser_resource[`wtk::Resource resource`] attribute.

Returns `true` on success, false if a parse error occurs.

----
virtual bool parseResource() = 0;
----

[#Parser_parseParameters]
=== `bool parseParameters()`
Parses the relation's parameters and sets the following attributes.

- xref:#Parser_gateSet[`wtk::GateSet gateSet`]
- xref:#Parser_featureToggles[`wtk::FeatureToggles featureToggles`]

Returns `true` on success, false if a parse error occurs.

WARNING:: `parseParameters()` should only be used if `resource == wtk::Resource::relation`.

----
virtual bool parseParameters() = 0;
----

[#Parser_parseHdrResParams]
=== `bool parseHdrResParams()`
This is a helper to call xref:#Parser_parseHeader[`parseHeader()`], xref:#Parser_parseResource[`parseResource()`], and, if necessary, xref:#Parser_parseParameters[`parseParameters()`] in sequence.

Returns `true` on success, false if a parse error occurs.

----
virtual bool parseHdrResParams() = 0;
----

[#Parser_version]
=== `struct { ... } version`
The version is the first line of an IR resource.
Although WizToolKit tends to be tied to a particular IR version, the Parser does not make any checks for the particular IR version.

The version consists of `major`, `minor`, and `patch` elements, all of type `size_t`.

----
struct {
  size_t major = 0;
  size_t minor = 0;
  size_t patch = 0;
} version;
----

[#Parser_characteristic]
=== `Number_T characteristic`
The field's prime modulus or "characteristic".
The parser does not check for primality.

----
Number_T characteristic = Number_T(0);
----

[#Parser_degree]
=== `size_t degree`
The field's degree.
The IR requires this to be `1`, although the parser does not test this.

----
size_t degree = 0;
----

[#Parser_resource]
=== `wtk::Resource resource`
The resource type which is currently being parsed.
This has type xref:{xref-rel-dir}api/wtk/IRParameters.adoc#enum_Resource[`wtk::Resource`].

----
wtk::Resource resource = Resource::invalid;
----

[#Parser_gateSet]
=== `wtk::GateSet gateSet`
The set of gates to be allowed within the relation.
This has type xref:{xref-rel-dir}api/wtk/IRParameters.adoc#struct_GateSet[`wtk::GateSet`].

WARNING:: `gateSet` may only be used if `resource == wtk::Resource::relation`.

----
wtk::GateSet gateSet;
----

[#Parser_featureToggles]
=== `wtk::FeatureToggles featureToggles`
The IR structural features to be allowed within the relation.
This has type xref:{xref-rel-dir}api/wtk/IRParameters.adoc#struct_FeatureToggles[`wtk::FeatureToggles`].

WARNING:: `featureToggles` may only be used if `resource == wtk::Resource::relation`.

----
wtk::FeatureToggles featureToggles;
----

[#Parser_arithmetic]
=== `wtk::ArithemticParser<Number_T>* arithmetic()`
This method returns a delegate parser for an arithmetic resource.

WARNING:: When parsing a relation, use of an arithmetic parser for parsing a non-arithmetic gateset will result in parse errors.

----
void wtk::ArithmeticParser<Number_T>*  arithmetic() = 0;
----

[#Parser_arithmetic64]
=== `wtk::ArithemticParser<uint64_t>* arithmetic()`
This method returns a delegate parser for an arithmetic resource. However the `Number_T` template is downgraded to a `uint64_t`.

WARNING:: When parsing a relation, use of an arithmetic parser for parsing a non-arithmetic gateset will result in parse errors.

----
void wtk::ArithmeticParser<uint64_t>*  arithmetic64() = 0;
----

[#Parser_arithmetic32]
=== `wtk::ArithemticParser<uint32_t>* arithmetic()`
This method returns a delegate parser for an arithmetic resource. However the `Number_T` template is downgraded to a `uint32_t`.

WARNING:: When parsing a relation, use of an arithmetic parser for parsing a non-arithmetic gateset will result in parse errors.

----
void wtk::ArithmeticParser<uint32_t>*  arithmetic32() = 0;
----

[#Parser_boolean]
=== `wtk::BooleanParser* boolean()`
This method returns a delegate parser for a boolean resource.

NOTE:: The `Number_T` template is removed for `wtk::BooleanParser`, and `uint8_t` is always used in its place.

WARNING:: When parsing a relation, use of a boolean parser for parsing a non-boolean gateset will result in parse errors.

----
void wtk::BooleanParser*  boolean() = 0;
----

[#struct_ArithmeticParser]
== `template<typename Number_T> struct ArithmeticParser`
This is a delegate parser for the body of an arithmetic IR resource.
Its interface is substantially similar to xref:#struct_BooleanParser[`wtk::BooleanParser`].
In general, this type should not be constructed, but rather obtained from xref:#Parser_arithmetic[`parser.arithmetic()`].

[#ArithmeticParser_parseStream]
=== `bool parseStream(wtk::ArithmeticStreamHandler<Number_T>* handler)`
Parses the body of an arithmetic IR-Simple relation, passing each gate off to the handler in a streaming fashion.
The xref:#Parser_resource[`parser.resource`] must be xref:{xref-rel-dir}api/wtk/IRParameters.adoc#enum_Resource[`wtk::Resource::relation`].

The xref:{xref-rel-dir}api/wtk/ArithmeticStreamHandler.adoc#class_ArithmeticStreamHandler[`handler`] parameter must be nonnull.
The method returns `false` on failure, including if either the xref:#Parser_gateSet[`parser.gateSet`] or xref:#Parser_featureToggles[`parser.featureToggles`] are violated.
It does not make any other well-formedness checks.

----
virtual bool parseStream(wtk::ArithmeticStreamHandler<Number_T>* handler) = 0;
----

[#ArithmeticParser_parseTree]
=== `wtk:IRTree<Number_T> parseTree()`
Parses the body of any arithmetic relation, constructing a xref:{xref-rel-dir}api/wtk/IRTree.adoc#api_IRTree[syntax tree].
The xref:#Parser_resource[`parser.resource`] must be xref:{xref-rel-dir}api/wtk/IRParameters.adoc#enum_Resource[`wtk::Resource::relation`].
If a parse failure occurs, `nullptr` is returned, including if either the xref:#Parser_gateSet[`parser.gateSet`] or xref:#Parser_featureToggles[`parser.featureToggles`] are violated.
It does not make any other well-formedness checks.

----
virtual wtk::IRTree<Number_T>* parseTree() = 0;
----

[#ArithmeticParser_instance]
=== `wtk::InputStream<Number_T>* instance()`
Returns an xref:#struct_InputStream[`wtk::InputStream<Number_T>*`] which will parse the instance one value at a time.
The xref:#Parser_resource[`parser.resource`] must be xref:{xref-rel-dir}api/wtk/IRParameters.adoc#enum_Resource[`wtk::Resource::instance`].

This method will never return `nullptr`, instead returned xref:#struct_InputStream[`wtk::InputStream<Number_T>*`] will return xref:#enum_StreamStatus[`wtk::StreamStatus::error`] as necessary.

----
virtual wtk::InputStream<Number_T>* instance() = 0;
----

[#ArithmeticParser_shortWitness]
=== `wtk::InputStream<Number_T>* shortWitness()`
Returns an xref:#struct_InputStream[`wtk::InputStream<Number_T>*`] which will parse the short witness one value at a time.
The xref:#Parser_resource[`parser.resource`] must be xref:{xref-rel-dir}api/wtk/IRParameters.adoc#enum_Resource[`wtk::Resource::shortWitness`].

This method will never return `nullptr`, instead returned xref:#struct_InputStream[`wtk::InputStream<Number_T>*`] will return xref:#enum_StreamStatus[`wtk::StreamStatus::error`] as necessary.

----
virtual wtk::InputStream<Number_T>* shortWitness() = 0;
----

[#struct_BooleanParser]
== `struct BooleanParser`
This is a delegate parser for the body of an boolean IR resource.
Its interface is substantially similar to xref:#struct_AritheticParser[`wtk::ArithmeticParser<Number_T>`].
In general, this type should not be constructed, but rather obtained from xref:#Parser_boolean[`parser.boolean()`].
Note that this struct is not parameterized by `Number_T`.
Instead anywhere the a field/numeric literal would be expected, `uint8_t` is used instead.

[#BooleanParser_parseStream]
=== `bool parseStream(wtk::BooleanStreamHandler* handler)`
Parses the body of an boolean IR-Simple relation, passing each gate off to the handler in a streaming fashion.
The xref:#Parser_resource[`parser.resource`] must be xref:{xref-rel-dir}api/wtk/IRParameters.adoc#enum_Resource[`wtk::Resource::relation`].

The xref:{xref-rel-dir}api/wtk/BooleanStreamHandler.adoc#class_BooleanStreamHandler[`handler`] parameter must be nonnull.
The method returns `false` on failure, including if either the xref:#Parser_gateSet[`parser.gateSet`] or xref:#Parser_featureToggles[`parser.featureToggles`] are violated.
It does not make any other well-formedness checks.

----
virtual bool parseStream(wtk::BooleanStreamHandler* handler) = 0;
----

[#BooleanParser_parseTree]
=== `wtk:IRTree<uint8_t> parseTree()`
Parses the body of any arithmetic relation, constructing a xref:{xref-rel-dir}api/wtk/IRTree.adoc#api_IRTree[syntax tree].
The xref:#Parser_resource[`parser.resource`] must be xref:{xref-rel-dir}api/wtk/IRParameters.adoc#enum_Resource[`wtk::Resource::relation`].
If a parse failure occurs, `nullptr` is returned, including if either the xref:#Parser_gateSet[`parser.gateSet`] or xref:#Parser_featureToggles[`parser.featureToggles`] are violated.
It does not make any other well-formedness checks.

----
virtual wtk::IRTree<uint8_t>* parseTree() = 0;
----

[#BooleanParser_instance]
=== `wtk::InputStream<uint8_t>* instance()`
Returns an xref:#struct_InputStream[`wtk::InputStream<uint8_t>*`] which will parse the instance one value at a time.
The xref:#Parser_resource[`parser.resource`] must be xref:{xref-rel-dir}api/wtk/IRParameters.adoc#enum_Resource[`wtk::Resource::instance`].

This method will never return `nullptr`, instead returned xref:#struct_InputStream[`wtk::InputStream<Number_T>*`] will return xref:#enum_StreamStatus[`wtk::StreamStatus::error`] as necessary.

----
virtual wtk::InputStream<uint8_t>* instance() = 0;
----

[#BooleanParser_shortWitness]
=== `wtk::InputStream<uint8_t>* shortWitness()`
Returns an xref:#struct_InputStream[`wtk::InputStream<uint8_t>*`] which will parse the short witness one value at a time.
The xref:#Parser_resource[`parser.resource`] must be xref:{xref-rel-dir}api/wtk/IRParameters.adoc#enum_Resource[`wtk::Resource::shortWitness`].

This method will never return `nullptr`, instead returned xref:#struct_InputStream[`wtk::InputStream<Number_T>*`] will return xref:#enum_StreamStatus[`wtk::StreamStatus::error`] as necessary.

----
virtual wtk::InputStream<uint8_t>* shortWitness() = 0;
----

[#struct_InputStream]
== `template<typename Number_T> struct InputStream`
The InputStream represents either an instance or a short witness, and and allows the user to consume one value at a time from the stream.
Do not attempt to construct one manually.
Instead retrieve one from xref:#ArithmeticParser_instance[`arithmeticParser.instance()`], xref:#ArithmeticParser_shortWitness[`arithmeticParser.shortWitness()`], xref:#BooleanParser_instance[`booleanParser.instance()`],  or xref:#BooleanParser_shortWitness[`booleanParser.shortWitness()`].

[#InputStream_next]
=== `StreamStatus next(Number_T* num)`
Consumes a single value from the stream, placing it in the `num` parameter.
This operation may fail if a parse error or the end of file is reached, returning an xref:#enum_StreamStatus[`wtk::StreamStatus`]  error code.

----
virtual StreamStatus next(Number_T* num) = 0;
----

[#InputStream_lineNum]
=== `size_t lineNum()`
If the parser supports line numbering, then this method returns the line number corresponding to the prior invocation of `this->next(...)`.
If line numbering is not supported then `0` is returned.

If `this->next(...)` has not been called, it returned `wtk::StreamStatus::end`, or it returned `wtk::StreamStatus::error` then `this->lineNum()` may return any of `0`, the line number on which the error or end occurred, or the line number of the most recent successful call to `this->next(...)`.

----
virtual size_t lineNum();
----

[#enum_StreamStatus]
== `enum StreamStatus`
This enumeration indicates the success or means of failure for an xref:#struct_InputStream[`wtk::InputStream<Number_T>`].
It may take one of the following values.

`wtk::StreamStatus::success`:: Successfully retrieved an item from the stream.
`wtk::StreamStatus::end`:: Reached the end of the stream.
`wtk::StreamStatus::error`:: A parse error occurred.
