# Copyright (C) 2021-2022 Stealth Software Technologies, Inc.
# FOR SIEVE PROGRAM USE ONLY

test-ubuntu-18:
  image: registry.stealthsoftwareinc.com/stealth/builder-images/ubuntu:18.04
  script:
    - make BUILD_TYPE=CI test
    - make clean
    - make BUILD_TYPE=CI CXX=clang++ test
    - make regression-test
    - make install
    - cd docs/6_sample_backends/ && make -j3 CXX=g++ && make clean && make -j3 CXX=clang++

test-ubuntu-20:
  image: registry.stealthsoftwareinc.com/stealth/builder-images/ubuntu:20.04
  script:
    - make BUILD_TYPE=CI test
    - make clean
    - make BUILD_TYPE=CI CXX=clang++ test
    - make regression-test
    - make install
    - cd docs/6_sample_backends/ && make -j3 CXX=g++ && make clean && make -j3 CXX=clang++

test-centos-stream8:
  image: registry.stealthsoftwareinc.com/stealth/builder-images/centos:stream8
  script:
    - make BUILD_TYPE=CI test
    - make clean
    - make BUILD_TYPE=CI CXX=clang++ test
    - make regression-test
    - make install
    - cd docs/6_sample_backends/ && make -j3 CXX=g++ && make clean && make -j3 CXX=clang++

test-rockylinux-8:
  image: registry.stealthsoftwareinc.com/stealth/builder-images/rockylinux:8
  script:
    - make BUILD_TYPE=CI test
    - make clean
    - make BUILD_TYPE=CI CXX=clang++ test
    - make regression-test
    - make install
    - cd docs/6_sample_backends/ && make -j3 CXX=g++ && make clean && make -j3 CXX=clang++

test-centos-7:
  image: registry.stealthsoftwareinc.com/stealth/builder-images/centos:7
  script:
    - make ENABLE_ANTLR=0 CMAKE_CMD=cmake3 BUILD_TYPE=CI test
    - PYTHONPATH="src/main/python" python3 src/test/python/regression_tests.py

test-nixos:
  image: registry.stealthsoftwareinc.com/stealth/wiztoolkit/wtk-nix
  script:
    - nix-build
    - 'nix-shell -p "python3.withPackages(ps: with ps; [numpy])" --run "PYTHONPATH=src/main/python python3 src/test/python/regression_tests.py result/bin/"'

static-analysis-centos-stream8:
  image: registry.stealthsoftwareinc.com/stealth/builder-images/centos:stream8
  script:
    - make static-analysis

static-analysis-rockylinux-8:
  image: registry.stealthsoftwareinc.com/stealth/builder-images/rockylinux:8
  script:
    - make static-analysis

pages:
  image: registry.stealthsoftwareinc.com/kimee/stealth-pages-theme
  script:
    - cd pages/
    - ./_scripts/download_content.sh
    - jekyll build -d ../public
  artifacts:
    paths:
      - public
  when: manual
