= WizToolKit
ifndef::xref-rel-dir[]
:xref-rel-dir: docs/
endif::[]

This is a collection of tools, provided by team Wizkit, for working with the SIEVE IR.
It In addition to a few command-line tools, it has an extensive C++ API for manipulating the SIEVE IR.

== Documentation
The xref:{xref-rel-dir}readme.adoc[WizToolKit Manual is available by clicking here].
Here are a few highlights.

* xref:{xref-rel-dir}0_intro.adoc[Intro] An overview of WizToolKit and the IR
* xref:{xref-rel-dir}1_parsing.adoc[WizToolKit Parsers tutorial] 
* xref:{xref-rel-dir}2_nails.adoc[NAILS]: an interpreter API to bridge ZK backends into the Circuit-IR
* xref:{xref-rel-dir}3_plugins/0_intro.adoc[Plugins] the Circuit-IR plugins
* Tools
** xref:{xref-rel-dir}4_tools/firealarm.adoc[wtk-firealarm] A non-ZK interpreter for the SIEVE IR, useful for debugging.
** xref:{xref-rel-dir}4_tools/press.adoc[wtk-press] A format converter for the SIEVE IR (text to flatbuffer or flatbuffer to text).
* xref:{xref-rel-dir}5_testcases.adoc[Test case generation scripts]
* xref:{xref-rel-dir}6_sample_backends/0_intro.adoc[Backend Sample Code] to get started with a backend implementation/integration.

== Installation
It uses `cmake` but a `Makefile` wraps everything up, downloads a few dependencies, calls tools which `cmake` can't use, etc.
Install should be as simple as `make` and `make install`.
See the xref:{xref-rel-dir}7_install.adoc[installation guide] for more info.

WARNING:: If you just ran `git pull`, and all of a sudden you can't build anymore try `make deps-clean && make`.

== Licensing
Copyright (C) 2020-2022 Stealth Software Technologies, Inc.
Licensed to you under the link:./license.md[MIT License].

This research was developed with funding from the Defense Advanced Research Projects Agency (DARPA) under Contract No. HR001120C0087.
The views, opinions, and/or findings expressed are those of the author(s) and should not be interpreted as representing the official views or policies of the Department of Defense or the U.S. Government.

**Distribution Statement "A":** Approved for Public Release, Distribution Unlimited.

== Contact
For questions, comments, or bugs please contact mailto:kimee@stealthsoftwareinc.com[Kimberlee Model] via email or on SIEVE internal Slack.
