version 1.0.0;
field characteristic 2 degree 1;
short_witness @begin
  // 32-bit LSB-first: 1234
  <1>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  // 32-bit LSB-first: 5678
  <1>;
  <1>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  <0>;
  // operation: subtract
  <1>;
@end
