[#api_bolt_Evaluator]
= BOLT Evaluator API
:toc:
:source-highlighter: pygments
:source-language: c++
:source_subs: attributes,specialchars,macros
ifndef::xref-rel-dir[]
:xref-rel-dir: ../../../
endif::[]

Include this API as

----
#include <wtk/bolt/Evaluator.h>
----

Members of this API live in the following namespace

----
namespace wtk { namespace bolt { ...
----

The BOLT API is parameterized on two templates.

`Number_T`:: This template is the same integer-like template which the xref:{xref-rel-dir}api/wtk/Parser.adoc#api_Parser[Parser API] uses for numeric literals.
`Wire_T`:: This template is an opaque structure supplied by the xref:{xref-rel-dir}api/wtk/bolt/Backend.adoc#api_bolt_Backend[Backend] for encapsulating data related to a wire.
The xref:{xref-rel-dir}api/wtk/bolt/Builder.adoc#api_bolt_Builder[Builder] requires it to be default constructible/destructible, and the Evaluator requires it be mutable/overwritable.

[#class_Evaluator]
== `class Evaluator`
The `wtk::bolt::Evaluator<Wire_T, Number_T>` class encapsulates the second phase of BOLT invocation.
It traverses the BOLT relation and "executes" each gate.
Thus, it is by definition _O(n)_ where _n_ is the total number of gates.

[#Evaluator_constructor]
=== `Evaluator(wtk::bolt::Backend<Wire_T, Number_T>* const b)`
The single constructor requires just a pointer to the xref:{xref-rel-dir}api/wtk/bolt/Backend.adoc#api_bolt_Backend[`wtk::bolt::Backend<Wire_T, Number_T>` implementation].

----
Evaluator(wtk::bolt::Backend<Wire_T, Number_T>* const b);
----

[#Evaluator_evaluate]
=== `bool evaluate(wtk::bolt::Bolt<Wire_T, Number_T>* const bolt, wtk::InputStream<Number_T>* const instance, wtk::InputStream<Number_T>* const witness)`
Evaluates a `wtk::bolt::Bolt<Wire_T, Number_T>` relation and returns `true` on success.
The bolt relation may be constructed using the xref:{xref-rel-dir}api/wtk/bolt/Builder.adoc#api_bolt_Builder[BOLT Builder].
It must also have two xref:{xref-rel-dir}api/wtk/Parser.adoc#struct_InputStream[``wtk::InputStream<Number_T>``s].
The first, `instance`, must not be `nullptr`, while the second, `witness`, may be `nullptr` for the cases where the witness is inaccessible to a verifier.

----
bool evaluate(Bolt<Wire_T, Number_T>* const bolt,
    wtk::InputStream<Number_T>* const instance,
    wtk::InputStream<Number_T>* const witness);
----
