[#tools_viz]
= Viz (Visualization)
ifndef::xref-rel-dir[]
:xref-rel-dir: ../
endif::[]

For assistance in visualizing the IR, we came up with an IR to https://graphviz.org[Graphviz] converter (called ``wtk-viz``).
``wtk-viz`` expects its input to be a relation, and produces a _dot_ graph as output.
It traverses the IR Syntax Tree, and in most cases makes a fairly naive translation into the Dot language.
In the case of for-loops, `wtk-viz` repeats the loop scope mappings for each iteration of the loop, as it shows a better picture of the web created by repeated mappings.

== Command Line Usage
``wtk-viz`` accepts arguments in a `[ options... ] <input.rel> [ <output.rel> ]` form.
These are the available options.

[horizontal]
``--fg <color>``:: Changes the color of nodes, edges, and text ("foreground") to the given HTML color.
``--bg <color>``:: Changes the color of the background to the given HTML color.
`-f`:: Use xref:{xref-rel-dir}api/wtk/flatbuffer/Parser.adoc#api_flatbuffer_Parser[FlatBuffers] to parse the binary relation (defaults to xref:{xref-rel-dir}api/wtk/irregular/Parser.adoc#api_irregular_Parser[Text/IRRegular]).
`-h` or `--help``:: Print the help text.
`-v` or `--version``:: Print the version information.

== Example invocations
`wtk-viz` is invoked first to produce _dot_ source, followed by the `dot` compiler to generate an image.
`dot` invocation may take a long time for large circuits.

----
wtk-viz relation_file.rel relation_graph.dot
dot -Tsvg relation_graph.dot -o relation_graph.svg
----
